import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next js, hunting coder" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <nav className={styles.mainNav}>
        <ul>
          <Link href='/'><a><li>Home</li></a></Link>
          <Link href='/contact'><a><li>Contact</li></a></Link>
          <Link href='/about'><a><li>About</li></a></Link>
          <Link href='/blog'><a><li>Blog</li></a></Link>
        </ul>
      </nav>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className="mySpan dummy">Hunting Coder</span>
        </h1>

        <div className={styles.imageWrapper}>
          <Image src='/homeimg.jpg' className={styles.myImg} height={345} width={518} />
        </div>

        <h2 className={styles.description}>
          A blog for hunting coders by a hunting coder
        </h2>

        <div>
          <h1>Popular Blogs</h1>
          <div className="blogItem">
            <h3>How to learn Js in 2022</h3>
            <p>js is the language desinged </p>
          </div>
          <div className="blogItem">
            <h3>How to learn Js in 2022</h3>
            <p>js is the language desinged </p>
          </div>
          <div className="blogItem">
            <h3>How to learn Js in 2022</h3>
            <p>js is the language desinged </p>
          </div>
          <div className="blogItem">
            <h3>How to learn Js in 2022</h3>
            <p>js is the language desinged </p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}
