import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next js, hunting coder" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className="mySpan dummy">Hunting Coder</span>
        </h1>

        <div className={styles.imageWrapper}>
          <Image src='/homeimg.jpg' className={styles.myImg} height={345} width={518} />
        </div>

        <h2 className={styles.description}>
          A blog for hunting coders by a hunting coder
        </h2>

        
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}
